"""
Tests unitaires pour le module md2html.
"""

import pytest
from unittest.mock import Mock, patch, mock_open
from pathlib import Path

from dyag.commands.md2html import (
    extract_code_blocks,
    convert_graphviz_to_svg,
    convert_plantuml_to_svg,
    convert_mermaid_to_svg,
    clean_svg_content,
    markdown_to_html_basic,
    wrap_html_document,
    convert_markdown_table,
    process_markdown_to_html
)


class TestExtractCodeBlocks:
    """Tests pour la fonction extract_code_blocks."""

    def test_extract_single_graphviz_block(self):
        """Test extraction d'un bloc Graphviz."""
        content = """# Title

```dot
digraph G {
    A -> B;
}
```

Some text."""
        blocks = extract_code_blocks(content)
        assert len(blocks) == 1
        assert blocks[0][0] == 'dot'
        assert 'A -> B' in blocks[0][1]

    def test_extract_multiple_blocks(self):
        """Test extraction de plusieurs blocs de différents types."""
        content = """
```graphviz
digraph G { A -> B; }
```

```plantuml
@startuml
A -> B
@enduml
```

```mermaid
graph TD
    A --> B
```
"""
        blocks = extract_code_blocks(content)
        assert len(blocks) == 3
        assert blocks[0][0] == 'graphviz'
        assert blocks[1][0] == 'plantuml'
        assert blocks[2][0] == 'mermaid'

    def test_extract_no_blocks(self):
        """Test avec aucun bloc de code."""
        content = "# Title\n\nJust some text without code blocks."
        blocks = extract_code_blocks(content)
        assert len(blocks) == 0

    def test_extract_ignores_other_code_blocks(self):
        """Test que les blocs non-diagrammes sont ignorés."""
        content = """
```python
def hello():
    print("Hello")
```

```dot
digraph G { A -> B; }
```
"""
        blocks = extract_code_blocks(content)
        assert len(blocks) == 1
        assert blocks[0][0] == 'dot'


class TestConvertGraphvizToSvg:
    """Tests pour la fonction convert_graphviz_to_svg."""

    @patch('dyag.commands.md2html.subprocess.run')
    def test_successful_conversion(self, mock_run):
        """Test conversion réussie."""
        mock_run.return_value = Mock(
            returncode=0,
            stdout=b'<svg>test</svg>'
        )

        result = convert_graphviz_to_svg('digraph G { A -> B; }')
        assert result == '<svg>test</svg>'
        mock_run.assert_called_once()

    @patch('dyag.commands.md2html.subprocess.run')
    def test_conversion_failure(self, mock_run):
        """Test échec de conversion."""
        mock_run.return_value = Mock(
            returncode=1,
            stderr=b'Error message'
        )

        result = convert_graphviz_to_svg('invalid dot code')
        assert result is None

    @patch('dyag.commands.md2html.subprocess.run')
    def test_dot_command_not_found(self, mock_run):
        """Test quand la commande dot n'est pas trouvée."""
        mock_run.side_effect = FileNotFoundError()

        result = convert_graphviz_to_svg('digraph G { A -> B; }')
        assert result is None

    @patch('dyag.commands.md2html.subprocess.run')
    def test_conversion_timeout(self, mock_run):
        """Test timeout lors de la conversion."""
        mock_run.side_effect = Exception("Timeout")

        result = convert_graphviz_to_svg('digraph G { A -> B; }')
        assert result is None


class TestCleanSvgContent:
    """Tests pour la fonction clean_svg_content."""

    def test_remove_xml_declaration(self):
        """Test suppression de la déclaration XML."""
        svg = '<?xml version="1.0"?>\n<svg>content</svg>'
        result = clean_svg_content(svg)
        assert '<?xml' not in result
        assert '<svg>content</svg>' in result

    def test_remove_doctype(self):
        """Test suppression du DOCTYPE."""
        svg = '<!DOCTYPE svg>\n<svg>content</svg>'
        result = clean_svg_content(svg)
        assert '<!DOCTYPE' not in result
        assert '<svg>content</svg>' in result

    def test_remove_generator_comments(self):
        """Test suppression des commentaires générés."""
        svg = '<!-- Generated by dot -->\n<svg>content</svg>'
        result = clean_svg_content(svg)
        assert '<!-- Generated' not in result

    def test_clean_complete_svg(self, sample_svg):
        """Test nettoyage d'un SVG complet."""
        result = clean_svg_content(sample_svg)
        assert '<svg' in result
        assert '<?xml' not in result


class TestMarkdownToHtmlBasic:
    """Tests pour la fonction markdown_to_html_basic."""

    def test_convert_headings(self):
        """Test conversion des titres."""
        md = "# H1\n## H2\n### H3\n#### H4"
        html = markdown_to_html_basic(md)
        assert '<h1>H1</h1>' in html
        assert '<h2>H2</h2>' in html
        assert '<h3>H3</h3>' in html
        assert '<h4>H4</h4>' in html

    def test_convert_bold_italic(self):
        """Test conversion du gras et italique."""
        md = "**bold** and *italic*"
        html = markdown_to_html_basic(md)
        assert '<strong>bold</strong>' in html
        assert '<em>italic</em>' in html

    def test_convert_inline_code(self):
        """Test conversion du code inline."""
        md = "This is `code` inline"
        html = markdown_to_html_basic(md)
        assert '<code>code</code>' in html

    def test_convert_unordered_list(self):
        """Test conversion des listes non ordonnées."""
        md = "- Item 1\n- Item 2\n- Item 3"
        html = markdown_to_html_basic(md)
        assert '<ul>' in html
        assert '<li>Item 1</li>' in html
        assert '<li>Item 2</li>' in html
        assert '</ul>' in html

    def test_convert_markdown_table(self):
        """Test conversion d'un tableau Markdown."""
        table = """| Header 1 | Header 2 |
|----------|----------|
| Cell 1   | Cell 2   |
| Cell 3   | Cell 4   |"""

        html = convert_markdown_table(table)
        assert '<table>' in html
        assert '<thead>' in html
        assert '<th>Header 1</th>' in html
        assert '<td>Cell 1</td>' in html


class TestWrapHtmlDocument:
    """Tests pour la fonction wrap_html_document."""

    def test_wrap_creates_full_html(self):
        """Test création d'un document HTML complet."""
        content = "<p>Test content</p>"
        html = wrap_html_document(content, "Test Title")

        assert '<!DOCTYPE html>' in html
        assert '<html lang="fr">' in html
        assert '<title>Test Title</title>' in html
        assert content in html
        assert '<body>' in html
        assert '</body>' in html

    def test_wrap_includes_css(self):
        """Test inclusion du CSS."""
        content = "<p>Test</p>"
        html = wrap_html_document(content)

        assert '<style>' in html
        assert 'font-family' in html
        assert '.diagram' in html


class TestProcessMarkdownToHtml:
    """Tests pour la fonction process_markdown_to_html."""

    def test_file_not_found(self, temp_dir):
        """Test avec un fichier inexistant."""
        non_existent = temp_dir / "non_existent.md"
        result = process_markdown_to_html(str(non_existent))
        assert result == 1

    def test_successful_conversion_simple_markdown(self, temp_dir, sample_markdown):
        """Test conversion réussie d'un Markdown simple."""
        md_file = temp_dir / "test.md"
        html_file = temp_dir / "test.html"

        md_file.write_text(sample_markdown, encoding='utf-8')

        result = process_markdown_to_html(str(md_file), str(html_file))

        assert result == 0
        assert html_file.exists()

        html_content = html_file.read_text(encoding='utf-8')
        assert '<h1>Titre principal</h1>' in html_content
        assert '<h2>Section 1</h2>' in html_content

    def test_conversion_without_output_path(self, temp_dir, sample_markdown):
        """Test conversion sans spécifier le chemin de sortie."""
        md_file = temp_dir / "test.md"
        md_file.write_text(sample_markdown, encoding='utf-8')

        result = process_markdown_to_html(str(md_file))

        assert result == 0
        expected_html = temp_dir / "test.html"
        assert expected_html.exists()

    @patch('dyag.commands.md2html.convert_graphviz_to_svg')
    def test_conversion_with_diagram(self, mock_convert, temp_dir, sample_markdown_with_graphviz):
        """Test conversion avec un diagramme."""
        mock_convert.return_value = '<svg>test diagram</svg>'

        md_file = temp_dir / "test.md"
        html_file = temp_dir / "test.html"

        md_file.write_text(sample_markdown_with_graphviz, encoding='utf-8')

        result = process_markdown_to_html(str(md_file), str(html_file))

        assert result == 0
        assert html_file.exists()

        html_content = html_file.read_text(encoding='utf-8')
        assert '<svg>test diagram</svg>' in html_content
        assert 'diagram-dot' in html_content

    def test_conversion_no_standalone(self, temp_dir, sample_markdown):
        """Test conversion sans document standalone."""
        md_file = temp_dir / "test.md"
        html_file = temp_dir / "test.html"

        md_file.write_text(sample_markdown, encoding='utf-8')

        result = process_markdown_to_html(
            str(md_file),
            str(html_file),
            standalone=False
        )

        assert result == 0
        html_content = html_file.read_text(encoding='utf-8')
        assert '<!DOCTYPE html>' not in html_content
        assert '<h1>Titre principal</h1>' in html_content
