"""
Command to convert a Markdown file (generated by project2md) back to project structure.

This module parses a Markdown file and recreates the original project structure by:
- Extracting file paths from headers
- Extracting code blocks
- Creating directories
- Writing files with extracted content
"""

import sys
from pathlib import Path
from typing import Optional, Set

from dyag.analysis.core.md2project_parser import Md2ProjectParser


def md2project(
    markdown_file: str,
    output_dir: Optional[str] = None,
    dry_run: bool = False,
    overwrite: bool = False,
    merge: bool = False,
    verbose: bool = False
) -> int:
    """
    Convert Markdown file (from project2md) back to project structure.

    Args:
        markdown_file: Path to Markdown file generated by project2md
        output_dir: Output directory for project (default: {project_name}/)
        dry_run: Show what would be done without creating files
        overwrite: Overwrite existing files
        merge: Merge with existing files (don't delete existing)
        verbose: Print detailed progress

    Returns:
        Exit code (0 for success, 1 for error)
    """
    md_path = Path(markdown_file).resolve()

    if not md_path.exists():
        print(f"Error: Markdown file '{markdown_file}' does not exist.", file=sys.stderr)
        return 1

    if not md_path.is_file():
        print(f"Error: '{markdown_file}' is not a file.", file=sys.stderr)
        return 1

    if verbose:
        print(f"[INFO] Parsing Markdown: {md_path}")

    try:
        # Parse Markdown
        parser = Md2ProjectParser(verbose=verbose)
        project = parser.parse_file(str(md_path))

        if verbose:
            print(f"[INFO] Project: {project.name}")
            print(f"[INFO] Files found: {len(project.files)}")

        # Validate structure
        issues = parser.validate_structure(project)
        if issues:
            print("[WARNING] Issues detected:")
            for issue in issues:
                print(f"  - {issue}")

        if not project.files:
            print("[ERROR] No files extracted from Markdown", file=sys.stderr)
            return 1

        # Determine output directory
        if output_dir is None:
            output_path = Path(project.name)
        else:
            output_path = Path(output_dir)

        output_path = output_path.resolve()

        if verbose:
            print(f"[INFO] Output directory: {output_path}")

        # Check if output directory exists
        if output_path.exists() and not merge:
            if not overwrite:
                print(
                    f"[ERROR] Output directory '{output_path}' already exists. "
                    f"Use --overwrite or --merge to continue.",
                    file=sys.stderr
                )
                return 1
            else:
                if verbose:
                    print(f"[WARNING] Overwriting existing directory: {output_path}")

        # Dry run mode
        if dry_run:
            print("[DRY RUN] Would create the following structure:\n")
            print(f"{output_path}/")
            for file_entry in project.files:
                file_path = output_path / file_entry.path
                size = len(file_entry.content.encode('utf-8'))
                print(f"  {file_entry.path} ({size} bytes, {file_entry.language or 'text'})")
            print(f"\n[DRY RUN] Total: {len(project.files)} files")
            return 0

        # Create project structure
        if verbose:
            print("\n[INFO] Creating project structure...")

        created_files = []
        skipped_files = []
        errors = []

        for file_entry in project.files:
            file_path = output_path / file_entry.path

            try:
                # Check if file exists and not overwriting
                if file_path.exists() and not overwrite and not merge:
                    skipped_files.append(file_entry.path)
                    if verbose:
                        print(f"[SKIP] {file_entry.path} (already exists)")
                    continue

                # Create parent directories
                file_path.parent.mkdir(parents=True, exist_ok=True)

                # Write file
                file_path.write_text(file_entry.content, encoding='utf-8')
                created_files.append(file_entry.path)

                if verbose:
                    size = len(file_entry.content.encode('utf-8'))
                    print(f"[CREATE] {file_entry.path} ({size} bytes)")

            except Exception as e:
                errors.append((file_entry.path, str(e)))
                print(f"[ERROR] Failed to create {file_entry.path}: {e}", file=sys.stderr)

        # Summary
        print(f"\n[SUCCESS] Project created: {output_path}")
        print(f"[INFO] Created: {len(created_files)} files")

        if skipped_files:
            print(f"[INFO] Skipped: {len(skipped_files)} files (already exist)")

        if errors:
            print(f"[WARNING] Errors: {len(errors)} files failed")
            for path, error in errors[:5]:  # Show first 5 errors
                print(f"  - {path}: {error}")
            if len(errors) > 5:
                print(f"  ... and {len(errors) - 5} more errors")

        # Return exit code based on errors
        return 1 if errors else 0

    except Exception as e:
        print(f"Error: Failed to convert Markdown to project: {e}", file=sys.stderr)
        if verbose:
            import traceback
            traceback.print_exc()
        return 1


def register_md2project_command(subparsers):
    """Register the md2project command."""
    parser = subparsers.add_parser(
        'md2project',
        help='Convert Markdown file (from project2md) back to project structure',
        description='Parse a Markdown file generated by project2md and recreate the original '
                    'project structure with all files and content. Perfect for restoring projects '
                    'from documentation or templates.'
    )

    parser.add_argument(
        'markdown_file',
        type=str,
        help='Markdown file generated by project2md'
    )

    parser.add_argument(
        '-o', '--output',
        type=str,
        default=None,
        help='Output directory for project (default: <project_name>/)'
    )

    parser.add_argument(
        '-n', '--dry-run',
        action='store_true',
        help='Show what would be done without creating files'
    )

    parser.add_argument(
        '--overwrite',
        action='store_true',
        help='Overwrite existing files and directories'
    )

    parser.add_argument(
        '--merge',
        action='store_true',
        help='Merge with existing directory (don\'t delete existing files)'
    )

    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Show detailed progress'
    )

    parser.set_defaults(func=lambda args: md2project(
        args.markdown_file,
        args.output,
        args.dry_run,
        args.overwrite,
        args.merge,
        args.verbose
    ))
